### PR TITLE
c2/cuda/groth16_srs.cuh: implement SRS cache with LRU eviction policy.

### PR DESCRIPTION
**Pull request by dot-asm**

### CODE REVIEW

**Comment by sandsentinel** [comment]
Looks good and tests in Bellperson and here pass. Would you like me to merge it?

**Comment by dot-asm** [comment]
Added a pair of **optional** commits and re-based just in case. Optional commits allow to bypass caching in case application already does it (looking at @vmx;-).

**Comment by dot-asm** [comment]
> it also wouldn't free things, if I keep holding onto it from the Rust side.

Correct. Eviction from the cache doesn't necessarily free the SRS, omitting the last reference does. The side effect from your viewpoint is that **if/when** you choose to drop your references, resources won't just become available. Which is likely to be counter-productive. Because the reason for dropping the references is more than likely to be to free some resources.

**Comment by dot-asm** [comment]
Merged.

**Pull request closed without merging**
