### PR TITLE
c2/src/lib.rs: add alternative generate_groth16_proofs entry point.

### PR DESCRIPTION
**Pull request by dot-asm**
New entry point takes a slice of FFI-friendly variant of ProvingAssignment as a way to pack arguments in a more "natural" way.

### CODE REVIEW

**Comment by dot-asm** [comment]
Take it for a spin! The new entry point should handle independent circuits now...

**Comment by dot-asm** [comment]
> The new entry point should handle independent circuits now...

... which renders the `debug_assert_eq!` in the bellman/.../prover.rs redundant. Well, since those are debug assertions the release build won't notice the difference...

**Comment by dot-asm** [comment]
> `debug_assert_eq!` in the bellman/.../prover.rs

And as for the non-debug assertion, the one that ensures equal a-s', and by extension b-s' and c-s' sizes. It's actually not a problem to accommodate different sizes... Provided that they all get padded to h-s' size... In other words `lg_domain_size` [in the new execute_ntt_msm_h method] would be calculated not from `abc_size`, but from `points_h.size()`.

**Comment by sandsentinel** [comment]
Looks good! Though when run with cuda-gdb it crashes at one of `cudaMalloc` calls. The main branch also crashes in the same manner. Seems completely fine when not run with cuda-gdb.

**Comment by dot-asm** [comment]
Any particular reason you tried under debugger? :-) Anyway, it says "out of memory" and it appears to be honest/genuine. The debugger reserves some memory for itself, and it seems to be sufficient to push the 10GB card over the edge. For reference, to identify the source issue `catch throw` at cuda-gdb prompt prior starting the application. It's dev_ptr_t initialization in `ntt_msm_h::execute_ntt_msm_h` that throws the exception.

**Comment by sandsentinel** [comment]
> Any particular reason you tried under debugger?

I was running the test in `c2/` and after a few runs it crashed with `SIGKILL`, so I tried the debugger. But maybe it just overlapped with another process and ran out of memory.

> The debugger reserves some memory for itself, and it seems to be sufficient to push the 10GB card over the edge.

Makes sense.

> For reference, to identify the source issue catch throw at cuda-gdb prompt prior starting the application. It's dev_ptr_t initialization in ntt_msm_h::execute_ntt_msm_h that throws the exception.

That's neat, thanks!

**Comment by dot-asm** [comment]
> it crashed with `SIGKILL`

Kernel can kill the process hogging the memory when "it feels threatened." Make it a habit to check output from `dmesg` to see if it's the case :-)

**Comment by dot-asm** [comment]
Merged.

**Pull request closed without merging**
